services:
  - type: web
    name: macicast-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGO_PUBLIC_URL
        value: "mongodb+srv://yarmaciercanyasin:ercan02.@macicast.jf27xhq.mongodb.net/macidb?retryWrites=true&w=majority&appName=macicast"
      - key: BACKEND_URL
        value: https://macicast-backend.onrender.com 